spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/publishment
spring.datasource.username=postgres
spring.datasource.password=AlperinGotu

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.format_sql=true